#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DigitalBProcess.Resource", IsApplication=true)]

namespace DigitalBProcess
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int activateBtn = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int activationCodeBox = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int activationStatus = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int buttonContainer = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int dlLocationTxt = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int goToPlayerBtn = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int listView1 = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int myButton = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int pathText = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int progressBar1 = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int stepTwoBtn = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int txtInternetCheck = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int videoView1 = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int wifiConnBtn = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int wifiName = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int wifiPass = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivationLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DownloadCollectionLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int StepOne = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int VideoPlayer = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int WifiConnectionLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
